version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: hehe123
      POSTGRES_DB: monitoring
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"   
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5     

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: userhehe@hehe.com
      PGADMIN_DEFAULT_PASSWORD: hehe123
    volumes:
      - pgadmin:/var/lib/pgadmin

  backend:
    build: ./agent
    ports:
      - "8010:8000"  
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: db
      DB_PASSWORD: hehe123
      DB_NAME: monitoring
    depends_on:
      db:
        condition: service_healthy
    restart: always

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml     
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  frontend:
    build: ./frontend
    ports:
      - "3002:3000"  

volumes:
  pgadmin:
  pgdata:
  prometheus_data:
  
    
   