groups:
  - name: usage_alerts
    rules:
      - alert: HighCPUUsage
        expr: sum(rate(cpu_usage_seconds_total[5m])) by (instance) > 0.8
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage is above 80% for more than 5 minutes."
