services:
  metric_collector:
    build: .
    restart: always
    networks:
      - monitoring
    environment:
      SERVER_ID: ${SERVER_ID}
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  monitoring:
   external: true